# default keybind
bindkey -e

# dir
setopt nonomatch # no glob expansion for *, ?, [ and ]
setopt auto_cd   # cd without cd
setopt autopushd # push dir automatically
setopt pushd_ignore_dups # do not push duplicated dir
setopt correct   # spelling correction for commands
WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=5000 # maximum number of in-memory history
SAVEHIST=5000 # maximum number of records in $HISTFILE
setopt share_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_reduce_blanks

# Completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # case-insensitive
zstyle ':completion:*' use-cache on # completion caches
# zstyle ':completion:*:functions' ignored-patterns '_*' # ignore completion for non-existant commands
# zstyle ':completion:*:cd:*' ignore-parents parent pwd # cd will never select the parent directory
zstyle ':completion:*:approximate:*' max-errors 3 numeric # fuzzy completion
zstyle ':completion:*' file-patterns '^package-lock.json:source-files' '*:all-files' # ignore `package-lock.json` from completion
zstyle ':completion:*:default' menu select=1 # highlight selection